# Generated by Django 2.2.1 on 2019-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_variation_category'),
        ('carts', '0006_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vartiation',
            field=models.ManyToManyField(blank=True, null=True, to='products.Variation'),
        ),
    ]
