# Generated by Django 2.2.1 on 2019-06-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190615_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImamge',
            new_name='ProductImage',
        ),
    ]
