# Generated by Django 2.2.1 on 2019-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190615_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(null=True, upload_to='static/media/'),
        ),
    ]
